//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
)

type versionInfo struct {
	FixedFileInfo struct {
		FileVersion    fixedVersion
		ProductVersion fixedVersion
	}
	StringFileInfo struct {
		FileVersion    string
		ProductVersion string
	}
}

type fixedVersion struct {
	Major int
	Minor int
	Patch int
	Build int
}

func main() {
	data, err := os.ReadFile("versioninfo.json")
	if err != nil {
		fatalf("read versioninfo.json: %v", err)
	}

	var info versionInfo
	if err := json.Unmarshal(data, &info); err != nil {
		fatalf("parse versioninfo.json: %v", err)
	}

	version := info.StringFileInfo.ProductVersion
	if version == "" {
		fatalf("StringFileInfo.ProductVersion is empty")
	}
	if version != info.StringFileInfo.FileVersion {
		fatalf("StringFileInfo.FileVersion %q does not match ProductVersion %q", info.StringFileInfo.FileVersion, version)
	}
	if !regexp.MustCompile(`^\d+\.\d+\.\d+$`).MatchString(version) {
		fatalf("ProductVersion %q must use MAJOR.MINOR.PATCH", version)
	}
	if info.FixedFileInfo.FileVersion != info.FixedFileInfo.ProductVersion {
		fatalf("FixedFileInfo FileVersion does not match ProductVersion")
	}
	if info.FixedFileInfo.ProductVersion.Build != 0 {
		fatalf("FixedFileInfo.ProductVersion.Build must be 0 for MAJOR.MINOR.PATCH releases")
	}
	fixed := fmt.Sprintf("%d.%d.%d",
		info.FixedFileInfo.ProductVersion.Major,
		info.FixedFileInfo.ProductVersion.Minor,
		info.FixedFileInfo.ProductVersion.Patch,
	)
	if fixed != version {
		fatalf("FixedFileInfo.ProductVersion %q does not match StringFileInfo.ProductVersion %q", fixed, version)
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by go generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package main\n\n")
	fmt.Fprintf(&out, "import (\n")
	fmt.Fprintf(&out, "\t\"fmt\"\n")
	fmt.Fprintf(&out, "\t\"io\"\n")
	fmt.Fprintf(&out, ")\n\n")
	fmt.Fprintf(&out, "const appVersion = %q\n\n", version)
	fmt.Fprintf(&out, "func printVersion(w io.Writer) {\n")
	fmt.Fprintf(&out, "\t_, _ = fmt.Fprintf(w, \"Dexgram %%s\\n\", appVersion)\n")
	fmt.Fprintf(&out, "}\n")

	if err := os.WriteFile("version.go", out.Bytes(), 0o644); err != nil {
		fatalf("write version.go: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
