// Code generated by go generate; DO NOT EDIT.

package main

import (
	"fmt"
	"io"
)

const appVersion = "0.4.12"

func printVersion(w io.Writer) {
	_, _ = fmt.Fprintf(w, "Dexgram %s\n", appVersion)
}
